name: Docs
on:
  push:
    branches: [ main ]
jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Generate Dokka
        run: ./gradlew dokkaHtml
